title: "Alessandro Checco"
description: "Academic page"
url: "https://AlessandroChecco.github.io"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-scholar

# Optional but commonly used with Minimal Mistakes
minimal_mistakes_skin: "default"

# Build settings
markdown: kramdown

author:
  avatar: "/assets/images/profile.jpg"

defaults:
  - scope:
      path: ""
    values:
      layout: single
      author_profile: true

scholar:
  source: _bibliography
  bibliography: references.bib
  bibliography_template: bib
  sort_by: year
  order: descending


